### PR TITLE
Add: `WorldOfOpenSource`

### LINKED ISSUE #506: Develop this World of Open-Source Section
### What would you like to share?

Build this **World of Open-Source** Section

image

Use this framer-motion animation to implement this but there will be multiple objects as specified in the design
https://codesandbox.io/s/framer-motion-drag-with-constraints-pjn6t

### Additional information

Refer to the Figma Design
https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=2330%3A7211&t=u23pNyuQlhrFByO2-1

### PR DESCRIPTION
**Pull request by sarkartanmay393**
## Description
**Take a look, and let me know where to improve.**

---
## Issue Ticket Number
Fixes #506 

---
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by sarkartanmay393** [comment]
@Debajyoti14 Hey, take a look here.

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@sarkartanmay393 There are a couple of changes
1. The animation we are looking for on the right side part is fluent like it will move slowly by default in the rectangular area and by dragging the element it should move from one side to another swiftly
2. The icons on the right side are a little bit bigger and uneven in size.
3. The background is not like that in the Figma design There is no black background wrapped around the component.

**Comment by sarkartanmay393** [comment]
@Debajyoti14 kindly look at it again, I have tried making it more fluent and strict inside the right box. With MUI icons, it's easier but if I want to import any `svg` or `png``, it doesn't work as intended **yet**.

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@sarkartanmay393 There is a bug
image
Also it should move by default from the start

**Comment by sarkartanmay393** [comment]
> @sarkartanmay393 There is a bug image Also it should move by default from the start

I'm working on animating it, but the bug you mentioned isn't displayed on localhost. But still, I've changed some code, can you approve the Vercal deploy once again

**Comment by Debajyoti14** [comment]
@sarkartanmay393 It's still happening

**Comment by sarkartanmay393** [comment]
@Debajyoti14 Now it's fixed, I hope.

**Comment by Debajyoti14** [comment]
@sarkartanmay393 Great Work
just make the logos a bit big and make the movement slower
It is very difficult to touch to drag it

**Comment by Debajyoti14** [comment]
@sarkartanmay393 Do one thing the movement is looking a bit absurd.
Just make sure the icons are more bigger and it should be stationary at any random pos within the box.

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@sarkartanmay393 
image
The icon coming out issue is still persisiting

**Comment by sarkartanmay393** [comment]
@Debajyoti14 
**I am seeing it fine**
**Can it be a browser issue?**


image

**Comment by Debajyoti14** [comment]
@Debajyoti14 Have you checked the deployment link or checking it locally???

**Comment by sarkartanmay393** [comment]
> you checked the deplo

https://clueless-4s5of04u7-officialcluelesscommunity-gmailcom.vercel.app/ this one

**Comment by sarkartanmay393** [comment]
@Debajyoti14

**Comment by Debajyoti14** [comment]
@sarkartanmay393 It's good to be merged
Make it responsive

**Comment by sarkartanmay393** [comment]
@Debajyoti14 I hope it works.

**Comment by Debajyoti14** [comment]
@sarkartanmay393 Still not responsive 
image

**Comment by sarkartanmay393** [comment]
@Debajyoti14 kindly check out deployments with attention, [deploy](https://clueless-clgrvsey9-officialcluelesscommunity-gmailcom.vercel.app/) this link is working just fine for me.

Screenshot_20230301-115423_Chrome

**Comment by sarkartanmay393** [comment]
@Debajyoti14 you can check it once again.

**Comment by Debajyoti14** [comment]
@sarkartanmay393 Great Work. It's not easy to make custom animation. Kudos to your HardWork.

**Comment by sarkartanmay393** [comment]
@Debajyoti14 See you on other PRs 👋🏼

**Pull request merged**
