### PR TITLE
Modified the UI of Hacktoberfest page

### PR DESCRIPTION
**Pull request by durgeshm01722**
## Description
I have modified the UI of Hacktoberfest page of Clueless Community website with some different gradient combination.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [X] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [X] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

---
# Screenshots 👇

Screenshot 2022-10-18 161722

Screenshot 2022-10-18 161734

Screenshot 2022-10-18 161748

### CODE REVIEW

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@durgeshm01722 Also change the How to win Swags and fix merge conflicts

**Comment by durgeshm01722** [comment]
Okay

**Comment by Debajyoti14** [comment]
@durgeshm01722 Can you increase the size of the image a bit??

**Comment by durgeshm01722** [comment]
Sure

**Comment by durgeshm01722** [comment]
Done 👍

Screenshot 2022-10-18 203725

**Review by Debajyoti14 — APPROVED** [review]

**Comment by Debajyoti14** [comment]
Congrats @durgeshm01722 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow this steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/) .
3. Go to profile section from the top right hand corner.



1. Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard !

And don’t forget to share your achievement with your friends.

**Comment by durgeshm01722** [comment]
**My Profile URL** - https://www.clueless.tech/profile/103863839958922066506
**PR merged by** - @Debajyoti14

**Pull request merged**
