### PR TITLE
bug: add targets for links

### LINKED ISSUE #367: Add target=_blank in Community Partners & Sponser Images
### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Anish-Sarawgi**
## Description
Added target=_blank in Community Partners & Sponser Images so that the links open in new Tab.

## Issue Ticket Number
Fixes #367 

---
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Review by Debajyoti14 — COMMENTED** [review]
@Anish-Sarawgi also add target blank in the 2nd image in community partners

**Comment by Anish-Sarawgi** [comment]
> @Anish-Sarawgi also add target blank in the 2nd image in community partners

Done👍

**Review by Debajyoti14 — APPROVED** [review]

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@Anish-Sarawgi Fix the deployment error
image

**Comment by Anish-Sarawgi** [comment]
> @Anish-Sarawgi Fix the deployment error image

@Debajyoti14 i have made the required changes. Hope now it works.

**Review by Debajyoti14 — APPROVED** [review]

**Comment by Debajyoti14** [comment]
Congrats @Anish-Sarawgi 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow this steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/) .
3. Go to profile section from the top right hand corner.



1. Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard !

And don’t forget to share your achievement with your friends.

**Comment by Anish-Sarawgi** [comment]
> Member

Hey @Debajyoti14,
This is my <a href="https://www.clueless.tech/profile/admin/110854968147792415689">Profile</a>  link.

**Comment by Anish-Sarawgi** [comment]
> Congrats @Anish-Sarawgi 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow this steps.
> 
> 1. Star this repository. ⭐
> 2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/) .
> 3. Go to profile section from the top right hand corner.
> 
> 
> 
> 1. Comment your profile URL under this comment tagging the person who merged your PR.
> 
> That’s it. Follow the leaderboard !
> 
> And don’t forget to share your achievement with your friends.

Hey @Debajyoti14 ,
This is my <a href="https://www.clueless.tech/profile/admin/110854968147792415689">Profile</a> link.

**Pull request merged**
