### PR TITLE
Redesigned the login page

### PR DESCRIPTION
**Pull request by rohan9024**
Here is the screenshot -->

image

### CODE REVIEW

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@rohan9024 Actually this doesn't look appealing as you have said, Kindly try experiment with the design like by adding Text and Image at the same side.
And also fix it for dark theme at once
image

**Comment by rohan9024** [comment]
@Debajyoti14 I think this looks best because if we try putting image and text on one side .......it doesn't look that good.

image


If you want then maybe I have to try out a different design then......

**Comment by Debajyoti14** [comment]
@rohan9024 If the design is not appealing, Leave it.
We will keep the previous login screen

**Comment by rohan9024** [comment]
@Debajyoti14 Now you compare the designs please.


Light theme in production -->

image


Light theme by me -->

image

Dark theme in production -->

image


Dark theme I have designed now-->

image

**Review by Debajyoti14 — APPROVED** [review]

**Comment by Debajyoti14** [comment]
@rohan9024 Why this is looking like this after deployment???
image

**Comment by rohan9024** [comment]
@Debajyoti14 I made changes before ...idk why this is happening......

**Comment by Debajyoti14** [comment]
@rohan9024 Can't merge if this looks like this. Try to find why it's happening

**Comment by rohan9024** [comment]
@Debajyoti14 Alright, working on it.

**Comment by rohan9024** [comment]
@Debajyoti14 This looks like this on my end

**Comment by Debajyoti14** [comment]
Congrats @rohan9024 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow this steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/) .
3. Go to profile section from the top right hand corner.



1. Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard !

And don’t forget to share your achievement with your friends.

**Pull request merged**
