### PR TITLE
added link to github profile on clicking name or profile image in leaderboard

### LINKED ISSUE #387: Go to github profile on click in leaderboard
## **Is your feature request related to a problem? Please describe.**
Now on clicking on any user in leaderboard, it's taking nowhere

## **Describe the solution you'd like**
I feel it's better if it redirects to corresponding GitHub profile.

### PR DESCRIPTION
**Pull request by SarveshPatil29**
## Description

Added links to the username and profile image so that on click them the user would be redirected to the github profile of that particular user

---
## Issue Ticket Number
Fixes #387 

---
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

@Rajdip019 please review the code and let me know if you need any changes.

### CODE REVIEW

**Comment by Debajyoti14** [comment]
@SarveshPatil29 Sorry, but another person is assigned in the issue. So, We will keep your PR in hold. In case he doesn't do a PR, We will merge yours

**Comment by SarveshPatil29** [comment]
> @SarveshPatil29 Sorry, but another person is assigned in the issue. So, We will keep your PR in hold. In case he doesn't do a PR, We will merge yours

okay, no worries

**Comment by SarveshPatil29** [comment]
@Debajyoti14 currently when you hover over the username in leaderboard there is no effect, the cursor should be set as pointer and some hover effect must be added. Can I work on this then?

**Comment by Debajyoti14** [comment]
@SarveshPatil29 Yes. Open an issue , I will assign you and also make sure the links in opening in new tab. Closing this issue...

**Comment by SarveshPatil29** [comment]
> @SarveshPatil29 Yes. Open an issue , I will assign you and also make sure the links in opening in new tab. Take a pull from the main to avoid conflicts...

sure

**Pull request closed without merging**
