### PR TITLE
Fix Icon colours in Profile Project Card -Issue #414

### PR DESCRIPTION
**Pull request by sumateja**
Fix for Issue 414

## Description
Fixed the icons dark mode issue for #414 . Now the icons show up correctly in Light & dark mode both.
---
## Issue Ticket Number
#414 

---
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by sumateja** [comment]
@Debajyoti14  Can you please approve
image

image

**Comment by Debajyoti14** [comment]
@sumateja Fix the deployment Errors
image

**Comment by Debajyoti14** [comment]
@sumateja any update?

**Comment by sumateja** [comment]
Yes give me some time its just small removal, bit busy today morning. I ll
check in in 2 hours

Thanks ,
Sumateja k

**Comment by sumateja** [comment]
@Debajyoti14 Please check now

**Review by Debajyoti14 — APPROVED** [review]

**Comment by Debajyoti14** [comment]
Congrats @sumateja 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow this steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/) .
3. Go to profile section from the top right hand corner.



1. Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard !

And don’t forget to share your achievement with your friends.

**Comment by sumateja** [comment]
http://localhost:3000/profile/admin/116387429323799693466 @Debajyoti14

**Comment by sumateja** [comment]
https://www.clueless.tech/profile/admin/116387429323799693466 @Debajyoti14

**Pull request merged**
