### PR TITLE
Devrajsinh03/scrollbar color

### PR DESCRIPTION
**Pull request by Devrajsinh03**
## Description

Added the theme color to the scrollbar.

---
## Issue Ticket Number
Fixes #(issue_number)

---
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

# screenshot
Screenshot 2022-10-16 at 5 53 34 PM

### CODE REVIEW

**Comment by Devrajsinh03** [comment]
@Debajyoti14 I have added a UI enhancement for scrollbar please check it out.

**Comment by Devrajsinh03** [comment]
@Debajyoti14 it is done

**Comment by Debajyoti14** [comment]
@Devrajsinh03 Make the scrollbar light as i reviewed

**Comment by Devrajsinh03** [comment]
Screenshot 2022-10-18 at 4 55 54 PM


- is this okay @Debajyoti14 ?

**Comment by Debajyoti14** [comment]
Congrats @Devrajsinh03 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow these steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/) .
3. Go to the profile section from the top right-hand corner.

Screenshot_2022-09-30_at_2 40 58_PM

1. Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard !

And don’t forget to share your achievement with your friends.

**Pull request merged**
