### PR TITLE
Fixed Navbar for mobile view

### LINKED ISSUE #383: Fix mobile view for Navbar
### Description

The login button is not required in the mobile view as there is already login option present in the hamburger. Also the toggle  theme button is overlapping with clueless logo.

### Screenshots

WhatsApp Image 2022-10-24 at 6 24 08 PM

### Additional information

I would like to work on it.

### PR DESCRIPTION
**Pull request by itsmeAnubhab**
## Description

image
image

---
## Issue Ticket Number
Fixes #383 

---
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by Debajyoti14** [comment]
@itsmeAnubhab I think it's necessary to keep the Login button on the Mobile screen so that People will login instead of surfing the website.
Any other way to fix it?
Decreasing the size of the button or something like that???

**Comment by itsmeAnubhab** [comment]
> @itsmeAnubhab I think it's necessary to keep the Login button on the Mobile screen so that People will login instead of surfing the website. Any other way to fix it? Decreasing the size of the button or something like that???

ok i'll try

**Comment by itsmeAnubhab** [comment]
don't merge yet.

**Comment by Debajyoti14** [comment]
@itsmeAnubhab closing for now

**Pull request closed without merging**
