### PR TITLE
Changed image colour to light pink

### LINKED ISSUE #308: Fix Guidelines Section in Dark Mode
### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gaut2003**
Changed Image colour to Light pink.

## Description
Changed the image colour for guidelines to pink, suitable for both dark and light backgrounds.

---
## Issue Ticket Number
Fixes #308 

---
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

---
# Checklist:
- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by gaut2003** [comment]
Please review the pull request @Debajyoti14

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@gaut2003 don't change the image color as it's breaking the light screen, Use a totally different image which goes well with both light and dark theme

image

**Comment by gaut2003** [comment]
I have done the needful changes. Kindly verify @Debajyoti14

**Review by Debajyoti14 — APPROVED** [review]

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@gaut2003 Adjust the image size and also remove its background
image

**Comment by gaut2003** [comment]
Please guide me I am not able to remove the background of this image. @Debajyoti14

**Comment by Debajyoti14** [comment]
@gaut2003 Go to remove.bg website, upload the image there.
You should get an image without background there

**Comment by gaut2003** [comment]
Thanks for your help @Debajyoti14 
I have removed the background and made the changes you requested.

**Comment by gaut2003** [comment]
@Debajyoti14 Please merge this.

**Comment by gaut2003** [comment]
@Debajyoti14 Please revert.

**Comment by Debajyoti14** [comment]
@gaut2003 Fix the Deployment Issue
image

**Comment by gaut2003** [comment]
@Debajyoti14 I have done it. Please check.

**Comment by Debajyoti14** [comment]
@gaut2003 Still deployment errors is there
image

**Comment by gaut2003** [comment]
But there are no syntactical errors or any other type of errors. @Debajyoti14 Please help

**Review by Debajyoti14 — APPROVED** [review]

**Comment by gaut2003** [comment]
Can you please add the medium tag to this issue. @Debajyoti14  because I think it is worth it.

**Comment by gaut2003** [comment]
Profile URL - https://www.clueless.tech/profile/admin/97660740
Merged by - @Debajyoti14

**Comment by Debajyoti14** [comment]
@gaut2003 Nope changing an image is considered into a easy task

**Comment by gaut2003** [comment]
Ok @Debajyoti14

**Pull request merged**
