### PR TITLE
Revamped Tutorial Hell Section

### PR DESCRIPTION
**Pull request by ARYA-RAY**
## Description

Revamped Tutorial Hell Section
---
## Issue Ticket Number
Fixes #(i502)

---
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by ARYA-RAY** [comment]
animations not yet added

**Comment by Debajyoti14** [comment]
@ARYA-RAY Fix the deployment errors

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@ARYA-RAY Great Job
Just make the left codepad a little smaller and align the Replay text with its icon and I think the text will be a little bit smaller as weel.
This small tweaks and it is good to be merged

**Comment by ARYA-RAY** [comment]
@Debajyoti14 made the changes in replay button alignment and code box size

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@ARYA-RAY Fix the padding for each breakpoint
image
Rest is great

**Comment by ARYA-RAY** [comment]
paddings fixed

**Pull request merged**
