### PR TITLE
created lacking skills

### PR DESCRIPTION
**Pull request by amdpt323**
## Created lacking skills section

image

there is one svg missing that I couldn't create myself and this is not yet mobile optimized have to add media query also I have just pushed so that I could get a review of over all and then I could improve it.
Thankyou
---
## 508
Fixes #()

---
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ *] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [ *] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [ *] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [* ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@amdpt323 Fix the deployment errors
image

**Comment by amdpt323** [comment]
@Debajyoti14 please look into this pr

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@amdpt323 
image
There are some layout issues
also fix the font and button

**Comment by amdpt323** [comment]
@Debajyoti14  
for the current source code im getting this as an output but idk why the deployment is showing some layout and image issue
image

**Comment by Debajyoti14** [comment]
@amdpt323 I exactly don't know the reason.
Can you try by removing the unnecessary mui components like Typography, Grid where we can use h1 or div instead.

**Comment by amdpt323** [comment]
@Debajyoti14  can you look into this

**Comment by Debajyoti14** [comment]
@amdpt323 The Typography is fixed now
But it's not Responsive and also the blue button need to be fixed
image

**Comment by amdpt323** [comment]
@Debajyoti14 i hope this update fixes all issue.

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@amdpt323

**Comment by Debajyoti14** [comment]
@amdpt323 
image
Not fixed yet

**Comment by amdpt323** [comment]
@Debajyoti14 last for today please check

**Comment by Debajyoti14** [comment]
@amdpt323 Fix this issue
image
and also I don't know why it's padding is not adjusted still now
image

**Comment by Debajyoti14** [comment]
@amdpt323 It's good to be merged
Fix this bottom space issue
image
and Add some space btw button and image in mobile view

**Comment by amdpt323** [comment]
@Debajyoti14 the bottom space you are mentioning is due to the upcomingEvent section do you want me to change that ?

**Pull request merged**
