### PR TITLE
Fixed Leaderboard in Dark Mode

### LINKED ISSUE #316: Fix Leaderboard in Dark mode
### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by RajKanani1206**
## Description
Fixed Leaderboard in Dark Mode
image

---
## Issue Ticket Number
Fixes #316 

---
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Review by Debajyoti14 — APPROVED** [review]

**Comment by Debajyoti14** [comment]
@RajKanani1206 Can you fix the merge conflicts?

**Comment by RajKanani1206** [comment]
@Debajyoti14 Done.

**Comment by Debajyoti14** [comment]
@RajKanani1206 The Leaderboard is now on maintenance due to some technical error. We will review and merge your PR once that gets sorted.

**Comment by Debajyoti14** [comment]
@RajKanani1206 Reopen this.

**Pull request closed without merging**
