### PR TITLE
Added the revamped section

### LINKED ISSUE #507: Build Revamped Open-Source Programs Section
### What would you like to share?

Build Revamped Open-Source Programs Section
Mention under which Open-Source Program you are contributing

image

### Additional information

Refer to the Figma Design
https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=2330%3A7211&t=u23pNyuQlhrFByO2-1

### PR DESCRIPTION
**Pull request by CS50X-RGB**
## Description

ADDED REVAMPED PORTION OF OPENSOURCE AND ADDED TO THE HOME SECTION FOR THE PREVIEW

---
## Issue Ticket Number
Fixes #507

---
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [ ] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [ ] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [X] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Review by CS50X-RGB — COMMENTED** [review]
Added the revamped  about Open Source 
image

**Comment by CS50X-RGB** [comment]
@Debajyoti14 plz review and mobile component

**Comment by Debajyoti14** [comment]
@CS50X-RGB Closing this issue.
Please make a PR in the Dev Branch as all the revamped changes are going to be live in Dev Branch

**Comment by CS50X-RGB** [comment]
> @CS50X-RGB Closing this issue.
> Please make a PR in the Dev Branch as all the revamped changes are going to be live in Dev Branch

Ohh okk

**Pull request closed without merging**
