### PR TITLE
Closes #493 `new/HeroSection`

### LINKED ISSUE #493: Hero Section Revamped UI
### Build the Hero Section
image

Design the responsive UI as it is there in the Figma file

### Additional information

Have a look at the Figma Design 
https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=2330%3A7211&t=u23pNyuQlhrFByO2-1

The globe on the right side can be implemented by using this package
https://www.npmjs.com/package/cobe

### PR DESCRIPTION
**Pull request by sarkartanmay393**
## Description

---
## Issue Ticket Number
Fixes #493 

---
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes needed to the documentation

---
## Screenshot
image

### CODE REVIEW

**Comment by sarkartanmay393** [comment]
@Debajyoti14
@bbsdevloper 

 It's done ✅

I'm hoping to get **hard** label on this PR.

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@sarkartanmay393 Increase top padding in mobile view
image

**Comment by Debajyoti14** [comment]
@sarkartanmay393 Horizontal Padding is too much adjust with other sections
image

**Comment by sarkartanmay393** [comment]
@Debajyoti14 I think now it's fine.

**Pull request merged**
