### PR TITLE
Fixed the grid overflow and updated design

### PR DESCRIPTION
**Pull request by rohan9024**
Here is how I fixed the issue-

https://user-images.githubusercontent.com/64919642/196126713-df786395-9f4c-4aaa-8e9c-9a840b8ec37d.mp4

### CODE REVIEW

**Comment by Debajyoti14** [comment]
@rohan9024 You should have changed the Stacks in a different PR but well fix the gradient color of the cards for this PR.

**Comment by Debajyoti14** [comment]
@rohan9024 Yes

**Comment by rohan9024** [comment]
@Debajyoti14 this looks coool broooooo😥

**Comment by rohan9024** [comment]
Alright np, I'll bring back the gradient

**Comment by Debajyoti14** [comment]
@rohan9024 just bring back the gradient bro 😂. It goes with the Hacktoberfest clueless theme

**Pull request closed without merging**
