### PR TITLE
Made some UI fixes on the leaderboard page

### PR DESCRIPTION
**Pull request by durgeshm01722**
## Description
I have fixed the search bar above the leaderboard. It was not properly styled for mobile view. The clear button was not properly positioned in the mobile view.

## Before 👇

Screenshot 2022-10-27 225426

## After 👇

Screenshot 2022-10-27 225438

<br/><br/>
Also, I have fixed a small UI glitch in the leaderboard. The left side of the 'PR Merged' column had rounded borders in the desktop view which wasn't looking good. So, removed that.

## Before 👇

Screenshot 2022-10-27 231950

## After 👇

Screenshot 2022-10-27 232037

---
## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [X] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [X] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by Debajyoti14** [comment]
@durgeshm01722 closing this PR as these clear and search button will not exist as dynamic searching feature is being implemented.

**Comment by durgeshm01722** [comment]
Okay, no problem 👍

**Comment by durgeshm01722** [comment]
But, the 'PR Merged' column has rounded borders on the left side in the desktop view which isn't looking good. This needs to be fixed. Shall I create another PR for solving this issue?

**Comment by durgeshm01722** [comment]
@Debajyoti14

**Pull request closed without merging**
