### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ARYA-RAY**
## Description

Responsive revamped Events section using NextJS and Typescript.
---
## Issue Ticket Number 494
Fixes #(494)

---
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
image
@ARYA-RAY  In the Event card, there is also a description field, which you have to integrate and also in smaller screen fix the text Timeline issue as in the image below

image

**Comment by ARYA-RAY** [comment]
bugs fixed, desc added

**Comment by Debajyoti14** [comment]
@ARYA-RAY Nicely done
image

Just fix this multiline issue, it will be good to merge

**Comment by ARYA-RAY** [comment]
@Debajyoti14 Should I move the timeline to the next line for smaller devices?

**Comment by Debajyoti14** [comment]
@ARYA-RAY Share the ss
How is it looking?

**Comment by Debajyoti14** [comment]
Congrats @ARYA-RAY 🎉, your PR got merged.

Don’t forget to star this repository. ⭐

**Pull request merged**
