### PR TITLE
added rewards info

### LINKED ISSUE #336: update the swags info
## **Is your feature request related to a problem? Please describe.**
At present, information about the swags is not updated.

## **Describe the solution you'd like**
Update the information in the Rewards&Swags section, and also ReadMore button is of no use now, add a github link to it.

### PR DESCRIPTION
**Pull request by saimaheshtaduri**
## Issue Ticket Number
Fixes #336 

---
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [ ] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [ ] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by saimaheshtaduri** [comment]
@Rajdip019 @Debajyoti14 please review it

**Review by Debajyoti14 — APPROVED** [review]

**Comment by Debajyoti14** [comment]
@saimaheshtaduri Fix the merge conflict

**Comment by saimaheshtaduri** [comment]
done @Debajyoti14

**Comment by Debajyoti14** [comment]
@saimaheshtaduri Fix the deployment errors
image

**Comment by saimaheshtaduri** [comment]
@Debajyoti14 I guess the deployement errors are fixed

**Pull request merged**
