### PR TITLE
Added the open source in components of home

### LINKED ISSUE #507: Build Revamped Open-Source Programs Section
### What would you like to share?

Build Revamped Open-Source Programs Section
Mention under which Open-Source Program you are contributing

image

### Additional information

Refer to the Figma Design
https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=2330%3A7211&t=u23pNyuQlhrFByO2-1

### PR DESCRIPTION
**Pull request by CS50X-RGB**
## Description

# Added the  open source component in home folder
---
## Issue Ticket Number
Fixes #507

---
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [X] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [ ] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by CS50X-RGB** [comment]
Screenshot from 2023-02-17 22-23-18
@Debajyoti14 made this on pc version

**Comment by CS50X-RGB** [comment]
Any updates??

**Review by bbsdevloper — CHANGES_REQUESTED** [review]
Issue 
1. Make correct import of files
2. Make the section responsive for mobile and tab view

Tip: 
Always try to code for mobile, tab, pc view simultaneously

**Comment by CS50X-RGB** [comment]
Okay I will do the changes will write the code for mobile and to conditional rendering

**Comment by CS50X-RGB** [comment]
@bbsdevloper @Debajyoti14 plz help i was doing changes from test branch which is showing update from origin/dev after git pull what to do??

**Comment by CS50X-RGB** [comment]
@Debajyoti14 It seems fine now I git pulled it's working fine now

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@CS50X-RGB 
Fix the build errors
image

**Comment by CS50X-RGB** [comment]
I have fixed it plz review again @Debajyoti14

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@CS50X-RGB It's showing like this
image

**Comment by CS50X-RGB** [comment]
Okk have to download the pictures

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
This is the original one
image
This is what we have achieved so far
image
Some small tweaks and it will be good to be merged
Like this section, the background is not black and the green splash effect should be behind the Cards
The Cards also need some padding to look accurately like the design and it's not fluidly responsive 
image
Fix the merge conflicts that's it

**Comment by CS50X-RGB** [comment]
@Debajyoti14 How to make this fluidly responsive can u give some idea I have used a hook and sending component accordingly. 😅

**Comment by Debajyoti14** [comment]
@CS50X-RGB You can make the Right Side image small a little small and also make sure it's looking appropriate also when it's in mobile view then switch components and also make sure the padding and all is good

**Comment by CS50X-RGB** [comment]
@Debajyoti14 all changes are done execpt the merge conflict 
image
i am doing git pull no changes are coming?

**Comment by Debajyoti14** [comment]
@CS50X-RGB 
image
Set the image at the extreme right and give some more inner padding in the card itself

**Comment by CS50X-RGB** [comment]
> @CS50X-RGB 
> image
> Set the image at the extreme right and give some more inner padding in the card itself

@Debajyoti14 okay got it

**Comment by CS50X-RGB** [comment]
Fixed the border radius of the card too!

**Pull request merged**
