### PR TITLE
fixed dark mode image

### PR DESCRIPTION
**Pull request by shivamgupta2020**

### CODE REVIEW

**Comment by shivamgupta2020** [comment]
**Dark mode :-**
image
**Light mode:-**
image

**Review by Debajyoti14 — APPROVED** [review]

**Review by Debajyoti14 — CHANGES_REQUESTED** [review]
@shivamgupta2020 Fix this deployment issues
image

**Comment by shivamgupta2020** [comment]
> @shivamgupta2020 Fix this deployment issues image

Null error fixed. Please try to merge pull request again.

**Review by Debajyoti14 — APPROVED** [review]

**Comment by Debajyoti14** [comment]
Congrats @shivamgupta2020 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow these steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/)
3. Go to the profile section from the top right-hand corner.



Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard!

And don’t forget to share your achievement with your friends.

**Comment by shivamgupta2020** [comment]
[https://www.clueless.tech/profile/admin/91847638](url)

**Pull request merged**
