### PR TITLE
Dynamic search

### LINKED ISSUE #388: Remove search button and show results on typing in searchbox
## **Is your feature request related to a problem? Please describe.**
Now the user has to click on search, to get results

## **Describe the solution you'd like**
Instead show the results on typing in searchbox.

*

---

*

### PR DESCRIPTION
**Pull request by saimaheshtaduri**
## Description

now the search results updates on input.

https://user-images.githubusercontent.com/53844369/198072241-dc9e9cbd-0411-4a8e-a552-7c22b2fad93f.mp4

---
## Issue Ticket Number
Fixes #388 

---
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [ ] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [ ] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/clueless-official-website/pulls) for the same update/change?
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by saimaheshtaduri** [comment]
@Rajdip019 @Debajyoti14 please review it.

**Review by Debajyoti14 — APPROVED** [review]

**Comment by Debajyoti14** [comment]
@saimaheshtaduri Fix the Merge Conflicts

**Comment by saimaheshtaduri** [comment]
@Debajyoti14 please review now

**Comment by Debajyoti14** [comment]
Congrats @saimaheshtaduri 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow this steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/) .
3. Go to profile section from the top right hand corner.



1. Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard !

And don’t forget to share your achievement with your friends.

**Pull request merged**
